### ISSUE TITLE
MicroPIEWeb doesn't make any response

### ISSUE THREAD

**Issue by danveno** [biosemantics/MicroPIEWeb#3]
Users report that MicroPIEWeb doesn't make any response.

**Comment by danveno** [comment]
The log file says:
Caused by: java.lang.NullPointerException
    at edu.arizona.biosemantics.micropie.web.server.process.file.ServerXmlModelFileCreator.createXML(ServerXmlModelFileCreator.java:262)
    at edu.arizona.biosemantics.micropie.web.server.process.file.ServerXmlModelFileCreator.createXmlModelFile(ServerXmlModelFileCreator.java:171)
    at edu.arizona.biosemantics.micropie.web.server.rpc.MicroPIEWebService.readXMLFiles(MicroPIEWebService.java:204)
    at edu.arizona.biosemantics.micropie.web.server.rpc.MicroPIEWebService.submitToMicroPIE(MicroPIEWebService.java:113)

It seems that there is something wrong with XML creation. 

I checked the input file and found that the problem may be caused by missing species name.  This should be addressed.

**Comment by danveno** [comment]
Fixed. Allow species name blank.
